<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Wannier90 – 3rdSPDM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./5_HOTI.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-efb83d8b435aa5b21c9543a531cde318.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-5ab5bd807e84b07578759617803a36f2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-efb83d8b435aa5b21c9543a531cde318.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./6_Wannier90.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Wannier90</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">3rdSPDM</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comentarios generales</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Estructura cristalina (cristal)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_tbh.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Aproximación de amarre fuerte</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_grafeno.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Grafeno</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_haldane.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelo de Haldane</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_KaneMele.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo Kane-Mele</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5_HOTI.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Aislates topológicos de orden superior</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6_Wannier90.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Wannier90</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#quantum-espresso" id="toc-quantum-espresso" class="nav-link active" data-scroll-target="#quantum-espresso"><span class="header-section-number">7.1</span> Quantum espresso</a></li>
  <li><a href="#lectura-usando-pythtb." id="toc-lectura-usando-pythtb." class="nav-link" data-scroll-target="#lectura-usando-pythtb."><span class="header-section-number">7.2</span> Lectura usando <code>pythtb</code>.</a>
  <ul class="collapse">
  <li><a href="#visualización-del-modelo" id="toc-visualización-del-modelo" class="nav-link" data-scroll-target="#visualización-del-modelo"><span class="header-section-number">7.2.1</span> Visualización del modelo</a></li>
  <li><a href="#estructura-de-bandas" id="toc-estructura-de-bandas" class="nav-link" data-scroll-target="#estructura-de-bandas"><span class="header-section-number">7.2.2</span> Estructura de bandas</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Wannier90</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="quantum-espresso" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="quantum-espresso"><span class="header-section-number">7.1</span> Quantum espresso</h2>
<pre><code>$ pw.x &lt; grafeno_scf.in &gt; grafeno_scf.out</code></pre>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>grafeno_scf.in
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>&amp;CONTROL
   calculation     =  'scf'
   restart_mode    =  'from_scratch'
   prefix          =  'grafeno'
   outdir          =  'tmp/'
   pseudo_dir      =  './'
/

&amp;SYSTEM
   ibrav           =  0
   ecutrho         =  1120
   ecutwfc         =  140
   nat             =  2
   nspin           =  1
   ntyp            =  1
   occupations     =  'smearing'
   smearing        =  'gaussian'
   degauss         =   2e-3
   tot_charge      =  0.0
   vdw_corr        =  'none'
 /

&amp;ELECTRONS
   conv_thr         =  1e-10
   diagonalization  =  'david'
   electron_maxstep =  1000
   mixing_beta      =  0.5
 /

&amp;IONS
/

&amp;CELL
/

ATOMIC_SPECIES
C    12.011    C.pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS {crystal}
C    0.000000000   0.000000000   0.250000000
C    0.333333333   0.333333333   0.250000000

CELL_PARAMETERS {angstrom}
   2.467306803  -0.000000000  -0.000000000
   1.233653402   2.136750370   0.000000000
   0.000000000  -0.000000000  19.999730020
   
K_POINTS {automatic}
18 18 1 0 0 0</code></pre>
</div>
</div>
</div>
<pre><code>$ pw.x &lt; grafeno_nscf.in &gt; grafeno_nscf.out</code></pre>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>grafeno_nscf.in
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>&amp;CONTROL calculation = ‘nscf’ restart_mode = ‘from_scratch’ prefix = ‘grafeno’ outdir = ‘tmp/’ pseudo_dir = ‘./’ /</p>
<p>&amp;SYSTEM ibrav = 0 ecutrho = 1120 ecutwfc = 140 nat = 2 nspin = 1 ntyp = 1 occupations = ‘smearing’ smearing = ‘gaussian’ degauss = 2e-3 tot_charge = 0.0 vdw_corr = ‘none’ nbnd = 16 /</p>
<p>&amp;ELECTRONS conv_thr = 1e-10 diago_full_acc = .true. /</p>
<p>&amp;IONS /</p>
<p>&amp;CELL /</p>
<p>ATOMIC_SPECIES C 12.011 C.pbe-n-kjpaw_psl.1.0.0.UPF</p>
<p>ATOMIC_POSITIONS {crystal} C 0.000000000 0.000000000 0.250000000 C 0.333333333 0.333333333 0.250000000</p>
<p>CELL_PARAMETERS {angstrom} 2.467306803 -0.000000000 -0.000000000 1.233653402 2.136750370 0.000000000 0.000000000 -0.000000000 19.999730020</p>
<p>K_POINTS crystal 144 0.00000000 0.00000000 0.00000000 6.94444444e-03 0.00000000 0.08333333 0.00000000 6.94444444e-03 0.00000000 0.16666667 0.00000000 6.94444444e-03 0.00000000 0.25000000 0.00000000 6.94444444e-03 0.00000000 0.33333333 0.00000000 6.94444444e-03 0.00000000 0.41666667 0.00000000 6.94444444e-03 0.00000000 0.50000000 0.00000000 6.94444444e-03 0.00000000 0.58333333 0.00000000 6.94444444e-03 0.00000000 0.66666667 0.00000000 6.94444444e-03 0.00000000 0.75000000 0.00000000 6.94444444e-03 0.00000000 0.83333333 0.00000000 6.94444444e-03 0.00000000 0.91666667 0.00000000 6.94444444e-03 0.08333333 0.00000000 0.00000000 6.94444444e-03 0.08333333 0.08333333 0.00000000 6.94444444e-03 0.08333333 0.16666667 0.00000000 6.94444444e-03 0.08333333 0.25000000 0.00000000 6.94444444e-03 0.08333333 0.33333333 0.00000000 6.94444444e-03 0.08333333 0.41666667 0.00000000 6.94444444e-03 0.08333333 0.50000000 0.00000000 6.94444444e-03 0.08333333 0.58333333 0.00000000 6.94444444e-03 0.08333333 0.66666667 0.00000000 6.94444444e-03 0.08333333 0.75000000 0.00000000 6.94444444e-03 0.08333333 0.83333333 0.00000000 6.94444444e-03 0.08333333 0.91666667 0.00000000 6.94444444e-03 0.16666667 0.00000000 0.00000000 6.94444444e-03 0.16666667 0.08333333 0.00000000 6.94444444e-03 0.16666667 0.16666667 0.00000000 6.94444444e-03 0.16666667 0.25000000 0.00000000 6.94444444e-03 0.16666667 0.33333333 0.00000000 6.94444444e-03 0.16666667 0.41666667 0.00000000 6.94444444e-03 0.16666667 0.50000000 0.00000000 6.94444444e-03 0.16666667 0.58333333 0.00000000 6.94444444e-03 0.16666667 0.66666667 0.00000000 6.94444444e-03 0.16666667 0.75000000 0.00000000 6.94444444e-03 0.16666667 0.83333333 0.00000000 6.94444444e-03 0.16666667 0.91666667 0.00000000 6.94444444e-03 0.25000000 0.00000000 0.00000000 6.94444444e-03 0.25000000 0.08333333 0.00000000 6.94444444e-03 0.25000000 0.16666667 0.00000000 6.94444444e-03 0.25000000 0.25000000 0.00000000 6.94444444e-03 0.25000000 0.33333333 0.00000000 6.94444444e-03 0.25000000 0.41666667 0.00000000 6.94444444e-03 0.25000000 0.50000000 0.00000000 6.94444444e-03 0.25000000 0.58333333 0.00000000 6.94444444e-03 0.25000000 0.66666667 0.00000000 6.94444444e-03 0.25000000 0.75000000 0.00000000 6.94444444e-03 0.25000000 0.83333333 0.00000000 6.94444444e-03 0.25000000 0.91666667 0.00000000 6.94444444e-03 0.33333333 0.00000000 0.00000000 6.94444444e-03 0.33333333 0.08333333 0.00000000 6.94444444e-03 0.33333333 0.16666667 0.00000000 6.94444444e-03 0.33333333 0.25000000 0.00000000 6.94444444e-03 0.33333333 0.33333333 0.00000000 6.94444444e-03 0.33333333 0.41666667 0.00000000 6.94444444e-03 0.33333333 0.50000000 0.00000000 6.94444444e-03 0.33333333 0.58333333 0.00000000 6.94444444e-03 0.33333333 0.66666667 0.00000000 6.94444444e-03 0.33333333 0.75000000 0.00000000 6.94444444e-03 0.33333333 0.83333333 0.00000000 6.94444444e-03 0.33333333 0.91666667 0.00000000 6.94444444e-03 0.41666667 0.00000000 0.00000000 6.94444444e-03 0.41666667 0.08333333 0.00000000 6.94444444e-03 0.41666667 0.16666667 0.00000000 6.94444444e-03 0.41666667 0.25000000 0.00000000 6.94444444e-03 0.41666667 0.33333333 0.00000000 6.94444444e-03 0.41666667 0.41666667 0.00000000 6.94444444e-03 0.41666667 0.50000000 0.00000000 6.94444444e-03 0.41666667 0.58333333 0.00000000 6.94444444e-03 0.41666667 0.66666667 0.00000000 6.94444444e-03 0.41666667 0.75000000 0.00000000 6.94444444e-03 0.41666667 0.83333333 0.00000000 6.94444444e-03 0.41666667 0.91666667 0.00000000 6.94444444e-03 0.50000000 0.00000000 0.00000000 6.94444444e-03 0.50000000 0.08333333 0.00000000 6.94444444e-03 0.50000000 0.16666667 0.00000000 6.94444444e-03 0.50000000 0.25000000 0.00000000 6.94444444e-03 0.50000000 0.33333333 0.00000000 6.94444444e-03 0.50000000 0.41666667 0.00000000 6.94444444e-03 0.50000000 0.50000000 0.00000000 6.94444444e-03 0.50000000 0.58333333 0.00000000 6.94444444e-03 0.50000000 0.66666667 0.00000000 6.94444444e-03 0.50000000 0.75000000 0.00000000 6.94444444e-03 0.50000000 0.83333333 0.00000000 6.94444444e-03 0.50000000 0.91666667 0.00000000 6.94444444e-03 0.58333333 0.00000000 0.00000000 6.94444444e-03 0.58333333 0.08333333 0.00000000 6.94444444e-03 0.58333333 0.16666667 0.00000000 6.94444444e-03 0.58333333 0.25000000 0.00000000 6.94444444e-03 0.58333333 0.33333333 0.00000000 6.94444444e-03 0.58333333 0.41666667 0.00000000 6.94444444e-03 0.58333333 0.50000000 0.00000000 6.94444444e-03 0.58333333 0.58333333 0.00000000 6.94444444e-03 0.58333333 0.66666667 0.00000000 6.94444444e-03 0.58333333 0.75000000 0.00000000 6.94444444e-03 0.58333333 0.83333333 0.00000000 6.94444444e-03 0.58333333 0.91666667 0.00000000 6.94444444e-03 0.66666667 0.00000000 0.00000000 6.94444444e-03 0.66666667 0.08333333 0.00000000 6.94444444e-03 0.66666667 0.16666667 0.00000000 6.94444444e-03 0.66666667 0.25000000 0.00000000 6.94444444e-03 0.66666667 0.33333333 0.00000000 6.94444444e-03 0.66666667 0.41666667 0.00000000 6.94444444e-03 0.66666667 0.50000000 0.00000000 6.94444444e-03 0.66666667 0.58333333 0.00000000 6.94444444e-03 0.66666667 0.66666667 0.00000000 6.94444444e-03 0.66666667 0.75000000 0.00000000 6.94444444e-03 0.66666667 0.83333333 0.00000000 6.94444444e-03 0.66666667 0.91666667 0.00000000 6.94444444e-03 0.75000000 0.00000000 0.00000000 6.94444444e-03 0.75000000 0.08333333 0.00000000 6.94444444e-03 0.75000000 0.16666667 0.00000000 6.94444444e-03 0.75000000 0.25000000 0.00000000 6.94444444e-03 0.75000000 0.33333333 0.00000000 6.94444444e-03 0.75000000 0.41666667 0.00000000 6.94444444e-03 0.75000000 0.50000000 0.00000000 6.94444444e-03 0.75000000 0.58333333 0.00000000 6.94444444e-03 0.75000000 0.66666667 0.00000000 6.94444444e-03 0.75000000 0.75000000 0.00000000 6.94444444e-03 0.75000000 0.83333333 0.00000000 6.94444444e-03 0.75000000 0.91666667 0.00000000 6.94444444e-03 0.83333333 0.00000000 0.00000000 6.94444444e-03 0.83333333 0.08333333 0.00000000 6.94444444e-03 0.83333333 0.16666667 0.00000000 6.94444444e-03 0.83333333 0.25000000 0.00000000 6.94444444e-03 0.83333333 0.33333333 0.00000000 6.94444444e-03 0.83333333 0.41666667 0.00000000 6.94444444e-03 0.83333333 0.50000000 0.00000000 6.94444444e-03 0.83333333 0.58333333 0.00000000 6.94444444e-03 0.83333333 0.66666667 0.00000000 6.94444444e-03 0.83333333 0.75000000 0.00000000 6.94444444e-03 0.83333333 0.83333333 0.00000000 6.94444444e-03 0.83333333 0.91666667 0.00000000 6.94444444e-03 0.91666667 0.00000000 0.00000000 6.94444444e-03 0.91666667 0.08333333 0.00000000 6.94444444e-03 0.91666667 0.16666667 0.00000000 6.94444444e-03 0.91666667 0.25000000 0.00000000 6.94444444e-03 0.91666667 0.33333333 0.00000000 6.94444444e-03 0.91666667 0.41666667 0.00000000 6.94444444e-03 0.91666667 0.50000000 0.00000000 6.94444444e-03 0.91666667 0.58333333 0.00000000 6.94444444e-03 0.91666667 0.66666667 0.00000000 6.94444444e-03 0.91666667 0.75000000 0.00000000 6.94444444e-03 0.91666667 0.83333333 0.00000000 6.94444444e-03 0.91666667 0.91666667 0.00000000 6.94444444e-03</p>
</div>
</div>
</div>
<pre><code>$ wannier90.x &lt; grafenowan.win &gt; grafenowan.wout</code></pre>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>grafenowan.win
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>use_ws_distance = .true.
!---------------------------GENERAL
num_bands = 16
num_wann  = 2
! exclude_bands = 1,2,3
!------------------------------CONV
num_iter  = 500
iprint    = 3
num_print_cycles = 50

!!! -- Disentanglement parameters -- !!!
!!! son rangos de energías sin recorrerse la EF !!!
dis_froz_min     = -4.0
dis_froz_max     =  0.0
dis_win_min      = -10.0
dis_win_max      =  14.0

!! To plot the WFs
! restart              =  plot
wannier_plot           =  true
wannier_plot_supercell =  3
write_hr  = true
write_xyz = true

!----------------------------SYSTEM
begin unit_cell_cart
Ang
2.467306803  -0.000000000  -0.000000000
1.233653402   2.136750370   0.000000000
0.000000000  -0.000000000  19.999730020
end unit_cell_cart

begin atoms_frac
C    0.000000000   0.000000000   0.250000000
C    0.333333333   0.333333333   0.250000000
end atoms_frac

begin projections
    C:pz
end projections

spinors = false

!----------------------------KPOINTS
! mismos puntos que en el nscf
mp_grid = 12 12 1
begin kpoints
0.00000000 0.00000000 0.00000000
0.00000000 0.08333333 0.00000000
0.00000000 0.16666667 0.00000000
0.00000000 0.25000000 0.00000000
0.00000000 0.33333333 0.00000000
0.00000000 0.41666667 0.00000000
0.00000000 0.50000000 0.00000000
0.00000000 0.58333333 0.00000000
0.00000000 0.66666667 0.00000000
0.00000000 0.75000000 0.00000000
0.00000000 0.83333333 0.00000000
0.00000000 0.91666667 0.00000000
0.08333333 0.00000000 0.00000000
0.08333333 0.08333333 0.00000000
0.08333333 0.16666667 0.00000000
0.08333333 0.25000000 0.00000000
0.08333333 0.33333333 0.00000000
0.08333333 0.41666667 0.00000000
0.08333333 0.50000000 0.00000000
0.08333333 0.58333333 0.00000000
0.08333333 0.66666667 0.00000000
0.08333333 0.75000000 0.00000000
0.08333333 0.83333333 0.00000000
0.08333333 0.91666667 0.00000000
0.16666667 0.00000000 0.00000000
0.16666667 0.08333333 0.00000000
0.16666667 0.16666667 0.00000000
0.16666667 0.25000000 0.00000000
0.16666667 0.33333333 0.00000000
0.16666667 0.41666667 0.00000000
0.16666667 0.50000000 0.00000000
0.16666667 0.58333333 0.00000000
0.16666667 0.66666667 0.00000000
0.16666667 0.75000000 0.00000000
0.16666667 0.83333333 0.00000000
0.16666667 0.91666667 0.00000000
0.25000000 0.00000000 0.00000000
0.25000000 0.08333333 0.00000000
0.25000000 0.16666667 0.00000000
0.25000000 0.25000000 0.00000000
0.25000000 0.33333333 0.00000000
0.25000000 0.41666667 0.00000000
0.25000000 0.50000000 0.00000000
0.25000000 0.58333333 0.00000000
0.25000000 0.66666667 0.00000000
0.25000000 0.75000000 0.00000000
0.25000000 0.83333333 0.00000000
0.25000000 0.91666667 0.00000000
0.33333333 0.00000000 0.00000000
0.33333333 0.08333333 0.00000000
0.33333333 0.16666667 0.00000000
0.33333333 0.25000000 0.00000000
0.33333333 0.33333333 0.00000000
0.33333333 0.41666667 0.00000000
0.33333333 0.50000000 0.00000000
0.33333333 0.58333333 0.00000000
0.33333333 0.66666667 0.00000000
0.33333333 0.75000000 0.00000000
0.33333333 0.83333333 0.00000000
0.33333333 0.91666667 0.00000000
0.41666667 0.00000000 0.00000000
0.41666667 0.08333333 0.00000000
0.41666667 0.16666667 0.00000000
0.41666667 0.25000000 0.00000000
0.41666667 0.33333333 0.00000000
0.41666667 0.41666667 0.00000000
0.41666667 0.50000000 0.00000000
0.41666667 0.58333333 0.00000000
0.41666667 0.66666667 0.00000000
0.41666667 0.75000000 0.00000000
0.41666667 0.83333333 0.00000000
0.41666667 0.91666667 0.00000000
0.50000000 0.00000000 0.00000000
0.50000000 0.08333333 0.00000000
0.50000000 0.16666667 0.00000000
0.50000000 0.25000000 0.00000000
0.50000000 0.33333333 0.00000000
0.50000000 0.41666667 0.00000000
0.50000000 0.50000000 0.00000000
0.50000000 0.58333333 0.00000000
0.50000000 0.66666667 0.00000000
0.50000000 0.75000000 0.00000000
0.50000000 0.83333333 0.00000000
0.50000000 0.91666667 0.00000000
0.58333333 0.00000000 0.00000000
0.58333333 0.08333333 0.00000000
0.58333333 0.16666667 0.00000000
0.58333333 0.25000000 0.00000000
0.58333333 0.33333333 0.00000000
0.58333333 0.41666667 0.00000000
0.58333333 0.50000000 0.00000000
0.58333333 0.58333333 0.00000000
0.58333333 0.66666667 0.00000000
0.58333333 0.75000000 0.00000000
0.58333333 0.83333333 0.00000000
0.58333333 0.91666667 0.00000000
0.66666667 0.00000000 0.00000000
0.66666667 0.08333333 0.00000000
0.66666667 0.16666667 0.00000000
0.66666667 0.25000000 0.00000000
0.66666667 0.33333333 0.00000000
0.66666667 0.41666667 0.00000000
0.66666667 0.50000000 0.00000000
0.66666667 0.58333333 0.00000000
0.66666667 0.66666667 0.00000000
0.66666667 0.75000000 0.00000000
0.66666667 0.83333333 0.00000000
0.66666667 0.91666667 0.00000000
0.75000000 0.00000000 0.00000000
0.75000000 0.08333333 0.00000000
0.75000000 0.16666667 0.00000000
0.75000000 0.25000000 0.00000000
0.75000000 0.33333333 0.00000000
0.75000000 0.41666667 0.00000000
0.75000000 0.50000000 0.00000000
0.75000000 0.58333333 0.00000000
0.75000000 0.66666667 0.00000000
0.75000000 0.75000000 0.00000000
0.75000000 0.83333333 0.00000000
0.75000000 0.91666667 0.00000000
0.83333333 0.00000000 0.00000000
0.83333333 0.08333333 0.00000000
0.83333333 0.16666667 0.00000000
0.83333333 0.25000000 0.00000000
0.83333333 0.33333333 0.00000000
0.83333333 0.41666667 0.00000000
0.83333333 0.50000000 0.00000000
0.83333333 0.58333333 0.00000000
0.83333333 0.66666667 0.00000000
0.83333333 0.75000000 0.00000000
0.83333333 0.83333333 0.00000000
0.83333333 0.91666667 0.00000000
0.91666667 0.00000000 0.00000000
0.91666667 0.08333333 0.00000000
0.91666667 0.16666667 0.00000000
0.91666667 0.25000000 0.00000000
0.91666667 0.33333333 0.00000000
0.91666667 0.41666667 0.00000000
0.91666667 0.50000000 0.00000000
0.91666667 0.58333333 0.00000000
0.91666667 0.66666667 0.00000000
0.91666667 0.75000000 0.00000000
0.91666667 0.83333333 0.00000000
0.91666667 0.91666667 0.00000000
end kpoints</code></pre>
</div>
</div>
</div>
</section>
<section id="lectura-usando-pythtb." class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="lectura-usando-pythtb."><span class="header-section-number">7.2</span> Lectura usando <code>pythtb</code>.</h2>
<section id="visualización-del-modelo" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="visualización-del-modelo"><span class="header-section-number">7.2.1</span> Visualización del modelo</h3>
<div id="fce28afe" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1"></a><span class="im">from</span> pythtb <span class="im">import</span> <span class="op">*</span> <span class="co"># import TB model class</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="im">from</span> pylab <span class="im">import</span> <span class="op">*</span></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="co">#import matplotlib.pyplot as plt</span></span>
<span id="cb6-4"><a href="#cb6-4"></a></span>
<span id="cb6-5"><a href="#cb6-5"></a>mpl.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> (<span class="fl">2.5</span>,<span class="fl">2.5</span>)</span>
<span id="cb6-6"><a href="#cb6-6"></a></span>
<span id="cb6-7"><a href="#cb6-7"></a>GR <span class="op">=</span> w90(<span class="vs">r"grafeno-qe"</span>,<span class="vs">r"grafenowan"</span>)</span>
<span id="cb6-8"><a href="#cb6-8"></a></span>
<span id="cb6-9"><a href="#cb6-9"></a>my_model <span class="op">=</span> GR.model(min_hopping_norm<span class="op">=</span><span class="fl">0.01</span>)</span>
<span id="cb6-10"><a href="#cb6-10"></a></span>
<span id="cb6-11"><a href="#cb6-11"></a>my_model.visualize(<span class="dv">0</span>,<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="6_Wannier90_files/figure-html/cell-2-output-1.png" width="246" height="229" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="estructura-de-bandas" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="estructura-de-bandas"><span class="header-section-number">7.2.2</span> Estructura de bandas</h3>
<div id="800a9af0" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Mostrar código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1"></a>path <span class="op">=</span> [[<span class="dv">2</span><span class="op">/</span><span class="dv">3</span>,<span class="dv">1</span><span class="op">/</span><span class="dv">3</span>,<span class="dv">0</span>],[<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>],[<span class="fl">0.5</span>,<span class="dv">0</span>,<span class="dv">0</span>]]</span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a>k_label<span class="op">=</span>(<span class="vs">r'</span><span class="dv">$</span><span class="vs">K</span><span class="dv">$</span><span class="vs">'</span>, <span class="vs">r'</span><span class="dv">$\G</span><span class="vs">amma</span><span class="dv">$</span><span class="vs">'</span>,<span class="vs">r'</span><span class="dv">$</span><span class="vs">M</span><span class="dv">$</span><span class="vs">'</span>)</span>
<span id="cb7-4"><a href="#cb7-4"></a></span>
<span id="cb7-5"><a href="#cb7-5"></a>(k_vec,k_dist,k_node)<span class="op">=</span>my_model.k_path(path,<span class="dv">1001</span>,report<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb7-6"><a href="#cb7-6"></a></span>
<span id="cb7-7"><a href="#cb7-7"></a>evals<span class="op">=</span>my_model.solve_all(k_vec)</span>
<span id="cb7-8"><a href="#cb7-8"></a></span>
<span id="cb7-9"><a href="#cb7-9"></a></span>
<span id="cb7-10"><a href="#cb7-10"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb7-11"><a href="#cb7-11"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(evals.shape[<span class="dv">0</span>]):</span>
<span id="cb7-12"><a href="#cb7-12"></a>    ax.plot(k_dist,evals[i],<span class="st">"k-"</span>)</span>
<span id="cb7-13"><a href="#cb7-13"></a><span class="cf">for</span> n <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(k_node)):</span>
<span id="cb7-14"><a href="#cb7-14"></a>    ax.axvline(x<span class="op">=</span>k_node[n],linewidth<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">'k'</span>)</span>
<span id="cb7-15"><a href="#cb7-15"></a></span>
<span id="cb7-16"><a href="#cb7-16"></a>ax.set_xlabel(<span class="st">"Path in k-space"</span>)</span>
<span id="cb7-17"><a href="#cb7-17"></a>ax.set_ylabel(<span class="st">"Band energy (eV)"</span>)</span>
<span id="cb7-18"><a href="#cb7-18"></a>ax.set_xlim(k_dist[<span class="dv">0</span>],k_dist[<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb7-19"><a href="#cb7-19"></a>ax.set_xticks(k_node)</span>
<span id="cb7-20"><a href="#cb7-20"></a>ax.set_xticklabels(k_label)</span>
<span id="cb7-21"><a href="#cb7-21"></a>fig.tight_layout()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="6_Wannier90_files/figure-html/cell-3-output-1.png" width="229" height="228" class="figure-img"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./5_HOTI.html" class="pagination-link" aria-label="Aislates topológicos de orden superior">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Aislates topológicos de orden superior</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="Referencias">
        <span class="nav-page-text">Referencias</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>